spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: jokail
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: jokail
    password: 1234

server:
  port: 8098